### ISSUE TITLE
Problems with simplified "hierarchy" of modules

### ISSUE THREAD

**Issue by KrisThielemans** [ETSInitiative/PETSIRD#119]
After #114, we have essentially a 2 level hierarchy, with current names of levels "module" and "elementary detecting elements" (where different types of "modules" are possible). Some "cons" are discussed in https://github.com/ETSInitiative/PETSIRD/issues/89#issuecomment-2869169361. Of those, I think the only problematic one is

> Less correspondence to actual physical set-up and potentially electronics. Example: if a scanner only measures singles histograms over a "physical module", we do not know how many singles where detected in each layer.

This problem potentially existed before #114, as there was no requirement for a "module" to correspond to any type of "measuring unit" (although I guess it was possible to encode a PETSIRD module to coincide with the "singles measuring unit" (there is currently no restriction on placements of "elementary detector elements" in the module, so there could be blocks/mini-blocks/layers etc inside, with potentially different types of detector materials and therefore properties, until #114).

**Comment by KrisThielemans** [comment]
I see 3 solutions:

# solution 1: record singles histograms either at "elementary detector level" or not at all.

Motivation: singles histograms are used for
1. for randoms-from-singles (RFS), for scanners that do not record delayeds.
2. computing singles dead-time

However, RFS needs "full singles histograms", and we encode dead-time (i.e., a PETSIRD user does not need to compute it). Therefore, with this proposal, we do have all necessary information.

# solution 2: introduce some kind of LUT to be able to encode hierarchies.

If singles histograms are not measured at the lowest level or at "PETSIRD module" level, we could have a list of "singles histogram measuring units", e.g. encoded as a list of lists of "PETSIRD modules":
- singles unit 1 consists of modules 1 and 2
- singles unit 2 consists of modules 3 and 4 and 5
- ...

This could be then be used for singles dead-time as well I guess, i.e. it could be stored per "singles unit" (to save some space).

# solution 3: change tack and encode hierarchies somehow anyway

**Comment by KrisThielemans** [comment]
Given that solution 1 feels a bit unsatisfactory (one could improve "randoms from delayeds" by using block/module-level singles), and that we won't go for solution 3, I've given solution 2 some more thought.

I think this can be done quite simply (naming can be improved):

```yaml
SinglesUnitIdx: int

# Lookup table giving singlesUnitIdx for every module (of a particular type)
# If -1, the singles are not measured
ModuleSinglesUnitIDLUT: SinglesUnitIdx[moduleIdx]

# Type alias for the index into singles units and their energy indices (for a specific module-type)
# The dimensions correspond to positional information (i.e. SinglesUnitIdx) and energy index. 
SinglesDetectionBin: unsigned

# Type for the histogram of singles of one type of module
# See SinglesHistogramTimeBlock and SinglesDetectionBin
SinglesHistogram: uint64[singlesDetectionBin]
```
See the current [SinglesHistogramTimeBlock](https://github.com/ETSInitiative/PETSIRD/blob/791fd17bb5ad2a3ff955467d07d4f06f145f6699/model/Protocol.yml#L200) and [SinglesHistogramLevelType](https://github.com/ETSInitiative/PETSIRD/blob/791fd17bb5ad2a3ff955467d07d4f06f145f6699/model/ScannerInformation.yml#L69) definitions.

Some things for discussion:
- `SinglesHistogramLevelType` could have 4 levels: (`none`, `severalModules`, `modules`, `all`) with the LUT not given of its `module`, or we could just have 3 levels, merging `severalModules and `modules` into 1. I think the latter is the simpler approach for documentation and implementation, and the size of the LUT is tiny anyway.
- use a similar structure for singles dead-time? (see above)
- Any other cases where this strategy could be used to generalise/simplify?
