### ISSUE TITLE
packaging of license file on pypi

### ISSUE THREAD

**Issue by gschramm** [ETSInitiative/PETSIRD#51]
@casperdcl Are we packaging the license file when we upload to pypi?

If we want to get the python package on conda-forge by grabbing it from pypi,
we need to have the license file on pypi.

**Comment by casperdcl** [comment]
yes we are https://github.com/ETSInitiative/PETSIRD/blob/ae3a0484a128f805a2143cc0d010d01557cf902f/python/pyproject.toml#L17 https://github.com/ETSInitiative/PETSIRD/blob/ae3a0484a128f805a2143cc0d010d01557cf902f/python/pyproject.toml#L24 https://pypi.org/project/petsird/

**Comment by gschramm** [comment]
The license need be packaged and we need to refer to the name of the file - so we need it (and I think also pypi appreciates it ;)
Can you copy + bundle "LICENSE.txt" from the repo when we publish to pypi?

Then I can include the exact file name in the recipe below (auto generated by grayskull)

```
{% set name = "petsird" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/petsird-{{ version }}.tar.gz
  sha256: 0cb6448409b828bb031485c3358a557764d4c0b96e454eba7739c825f35f562c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - numpy >=1.22

test:
  imports:
    - petsird
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Library and tools for working with PET Emission Tomography Standardization Initiative Raw Data (PETSIRD) data
  license: Apache-2.0
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - gschramm

```
