### ISSUE TITLE
conda-forge

### ISSUE THREAD

**Issue by KrisThielemans** [ETSInitiative/PETSIRD#60]
Now that we're on PyPI, we want to be on conda-forge as well. Ideally, we want both Python and C++, possibly in different packages?

- Currently, the generated C++ is just the source (no need to compile), so this could be "easy".
- I guess Python-only could just use the PyPI package.

I'm not sure what the best strategy is here. @casperdcl @gschramm @johnstairs @naegelejd suggestions?

**Comment by casperdcl** [comment]
See #37 for discussion

**Comment by gschramm** [comment]
If we have the C++ / python sources available in a tagged gh version, creating the recipe "should be easy".

We should decide whether we want to have one package including C++ and python, or to have 2 packages.
The latter has the advantage that we can auto-create a conda-forge recipe getting the sources from pypi.

**Comment by gschramm** [comment]
auto generation of the conda-forge recipe for petsird python package now works :)

If we agree to have separate python and C++ packages on conda-forge, I can stage the python recipe below and list 
@KrisThielemans @casperdcl , me, ... as maintainers.

```
{% set name = "petsird" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/petsird-{{ version }}.tar.gz
  sha256: a5d346b1e0a594fa1ab3c5a630e7f24e3fc33a60bcce801aeb06f5648c997b68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.9
    - numpy >=1.22

test:
  imports:
    - petsird
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Library and tools for working with PET Emission Tomography Standardization Initiative Raw Data (PETSIRD) data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
```
