### ISSUE TITLE
change (detector_id, energy_window_idx) to a single index?

### ISSUE THREAD

**Issue by KrisThielemans** [ETSInitiative/PETSIRD#82]
In the current representation, we separate spatial and energy indices. This is potentially wasteful, especially if there is only 1 energy window (which is the most common way). In current (and near-future) yardl, this means every coincidence-event currently uses (at least) 2 bytes for energy information.

A way to resolve this is to combine the two into 1 linear index. As long as we require that the number of energy windows is the same for every type of module (which is probably reasonable), the conversion between the 2 is easy enough ( lin_index = energy_idx + num_energy_windows * detector_id).

**Comment by MaxTousss** [comment]
It seems like uint in Yardl are uint32, so it might be possible to even include TOF in that without busting the limit. However, this come at a cost of more operations to access the detectorId which make slow significantly the processing of a list mode. 

Would it be possible to encode energy window and tof in a smaller integer? unit8 might not be enough for users that desire a really fine discretization but unit16 would be clearly enough and it would save "1.5 uint32" per coincidence.

**Comment by KrisThielemans** [comment]
>  it might be possible to even include TOF in that.

We cannot easily fold tof into the current indices, as there's a pair of indices, and a single tof index. I suppose we could combine 2 energy indices into 1 (running to numEnergyBins^2) (which could then be combined with the tof index). We'd have to be very clear about order then (not so easy as you'd hope, given MATLAB vs C/Python differences). It will also become a bit more messy for TripleCoincidences.

> Would it be possible to encode energy window and tof in a smaller integer?

My understanding is that for the binary format generated by yardl, "variable length integers" are used, so it wouldn't make any difference. Presumably, for HDF5 or so, it would, so definitely good idea to use `uint16` for those. @johnstairs  @naegelejd could you confirm?

**Comment by KrisThielemans** [comment]
ETSI meeting 21Mar2025 discussion:

- con-argument: simplicity for decoding
- pro-argument: backwards compatibility: if in PETSIRD v2, we would want to add another property (e.g. photon polarization) via another dimension, then the entire code should be rewritten when using multiple indices, even if the scanner doesn’t support this extra property, while with a single index, change is only necessary if the extra property changes value. 

Documentation issues could be simplified by introducing a new type for the combined index, e.g. `DetectionBin`. This
https://github.com/ETSInitiative/PETSIRD/blob/8c4b1bd9703b25bc9de2af2d66051380e3286be2/model/CoincidenceEvent.yml#L3-L10
would then change to
```yml
CoincidenceEvent: !record
  fields:
    # bin numbers for the two detections (see doc for DetectionBin)
    detBin: DetectionBin*2
    # an index into the tofBinEdges field in the ScannerInformation
    tofIdx: uint
```
This is a good idea anyway.

**Comment by KrisThielemans** [comment]
>Documentation issues could be simplified by introducing a new type for the combined index, e.g. DetectionBin. 

This was implemented in #105

**Comment by KrisThielemans** [comment]
> pro-argument: backwards compatibility: if in PETSIRD v2, we would want to add another property ...

An alternative for "future proofing" would be to store extra properties in separate fields:
```yaml
CoincidenceEventSpatialInfo: !record
  field:
    detElIndices: DetElIdx*2
    tof: uint

EventTimeBlock: !record
  fields:
    promptEventsSpatialInfo: CoincidenceEventSpatialInfo*
    # energy window indices for every event in the previous list
    promptEventsEnergyInfo: EnergyIndexPair*
    someFancyPropertyInfo: FancyIndexPair*
    ...
 ```

- Advantage: hardly any space overhead (if no energy windows or fancy property is present, we just have 2 empty arrays)
- Disadvantage: data definition is probably less clear. I don't see any obvious way to extend this trick to the arrays in  the headers/singles histograms etc. (except by reserving a 3rd dimension for the fancy property)
